---
- hosts: web
  tasks:
    - name: stop nginx
      service:
          name: nginx
          state: stopped
    - name: ensure nginx is not installed
      apt: name=nginx state=absent
    - name: Delete content & directory
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - /etc/nginx/sites-available/static_site.cfg
        - /etc/nginx/sites-enabled/default
        - /home/ubuntu/sites
